{{- include "cert-manager-bunny.validate" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cert-manager-bunny.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ include "cert-manager-bunny.name" . }}
type: Opaque
data:
  accessKey: {{ .Values.bunny.apiKey | b64enc | quote }}
