apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager-bunny.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cert-manager-bunny.name" . }}-webhook
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: https
    protocol: TCP
    name: https
  selector:
    app.kubernetes.io/name: {{ include "cert-manager-bunny.name" . }}-webhook
    app.kubernetes.io/instance: {{ .Release.Name }}
